import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', e => errors.push('PAGEERROR ' + e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto('http://localhost:4173/');
await page.waitForTimeout(6000);
await page.screenshot({ path: '/tmp/shots/v2-01-title.png' });
await page.click('#intro-start', { timeout: 60000 });
await page.evaluate(() => { const { customers } = window.__casino; customers.queue(6); window.__casino.step(45); });
await page.evaluate(() => { const { player, world } = window.__casino; player.camDist = 9; player.camPitch = 0.5; player.teleport(0, world.D / 2 - 4); });
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/shots/v2-02-floor.png' });
await page.evaluate(() => { const { player, world } = window.__casino; player.camYaw = Math.PI; player.camDist = 10; player.camPitch = 0.4; player.teleport(0, world.D / 2 - 6); });
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/shots/v2-03-lookback.png' });
await page.evaluate(() => { const { player, world } = window.__casino; player.camYaw = 0; player.camDist = 14; player.camPitch = 0.35; player.teleport(5, world.D / 2 + 7); });
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/shots/v2-04-outside.png' });
console.log('errors:', errors.length ? errors.slice(0, 10) : 'none');
await browser.close();
